version: "3"

services:
  postgres:
    image: postgres:12.12
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
